#!/bin/bash





## description
# Commit to the master branch of whamcloud. 
# Uses the command from the whamcloud wiki at https://wiki.whamcloud.com/
# Currently at https://wiki.whamcloud.com/display/PUB/Using+Gerrit
# Adds hooks from the lustre project 

# cpoy-pasted from the whamcloud wiki, note that ${USER} is substituted from env
# a password will still be required
PUSH_COMMAND="git push ssh://${USER}@review.whamcloud.com:29418/fs/lustre-release HEAD:refs/for/master"

push_to_whamcloud_master() {
    $PUSH_COMMAND
}


SUFFIX=deactivated
LUSTRE=~/lustre-release
HOOKS_DIR=$LUSTRE/.git/hooks
CONTRIB_HOOKS_DIR=$LUSTRE/contrib/git-hooks

# add the whamcloud hooks to .git hooks for lustre
# commit-msg
# prepare-commit-msg
# if they are already in the correct directory but suffixed
# with deactivation suffix ($SUFFIX) remove the suffix so they become active
# if they aren't in the hooks sirectory at all, get them from
# the lustre source
add_hook_file() {
    # check if hook file exists, if so do nothing
    if [ -e "$HOOKS_DIR/$1" ]
    then
	echo "$1 already exists in $HOOKS_DIR"

    # if $SUFFIX activate it
    elif [ -e "$HOOKS_DIR/$1.$SUFFIX" ]
    then
	mv "$HOOKS_DIR/$1.$SUFFIX" "$HOOKS_DIR/$1"

    # if non-existent, copy it from the lustre source 
    else
	cp "$CONTRIB_HOOKS_DIR/$1" "$HOOKS_DIR/$1"
    fi
}


# deactivate the whamcloud (or any other) git hooks if they exist
# by adding $SUFFIX to the file names
# commit-msg
# prepare-commit-msg
# add ".deactivated" to them
remove_hook_file() {
    if [ -e "$HOOKS_DIR/$1" ]
    then
	mv "$HOOKS_DIR/$1" "$HOOKS_DIR/$1.$SUFFIX"	
    fi
}


add_hook_file "commit-msg"
add_hook_file "prepare-commit-msg"

push_to_whamcloud_master

remove_hook_file "commit-msg"
remove_hook_file "prepare-commit-msg"





